services:
    - type: web
      name: backend
      env: python
      buildCommand: pip install -r backend/requirements.txt
      startCommand: python backend/app.py
      envVars:
          - key: PYTHON_VERSION
            value: 3.11.3
          - key: PORT
            value: 8501

    - type: web
      name: frontend
      env: node
      buildCommand: npm install
      startCommand: npm start
